version: "3"

services:
  app:
    build: .
    working_dir: /myapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DOCKER_LOCAL=true
  db:
    restart: 'always'
    image: postgres:10.2-alpine
    ports:
      - 5432:5432
    environment:  
      - POSTGRES_USER=foster
      - POSTGRES_PASSWORD=roster
    volumes: 
      - ./docker/data/.data/postgres:/var/lib/postgresql/data
  cache:
    image: redis:3.2
    ports:
      - 6381:6379
    volumes:
      - ./docker/containers/cache/.data:/data
