version: "3"

services:
  app:
    build: .
    working_dir: /myapp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
      - elasticsearch
    environment:
      - DOCKER_LOCAL=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://cache:6379
  db:
    restart: 'always'
    image: postgres:10.2-alpine
    ports:
      - 5432:5432
    environment:  
      - POSTGRES_USER=foster
      - POSTGRES_PASSWORD=roster
    volumes: 
      - ./docker/data/.data/postgres:/var/lib/postgresql/data
  cache:
    image: redis:3.2
    ports:
      - 6379:6379
    volumes:
      - ./docker/containers/cache/.data:/data
  elasticsearch:
    image: elasticsearch:6.7.2
    ports:
      - "9200:9200"
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
networks:
  default:
    external:
      name: roster-local